name: "Publish Common"

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: "Publish"
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ inputs.tag }}
          access: public
          provenance: true
