name: "Publish Stable"

on:
  workflow_run:
    workflows:
      - "Bump Minor"
    types:
      - completed

concurrency:
  group: publish-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/publish-common.yml
    with:
      tag: latest
      ref: ${{ github.event.workflow_run.head_sha }}
    secrets: inherit
