name: "Publish Prerelease"

on:
  workflow_run:
    workflows:
      - "Bump Alpha"
      - "Bump Beta"
    types:
      - completed

concurrency:
  group: publish-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/publish-common.yml
    with:
      tag: ${{ github.event.workflow_run.name == 'Bump Alpha' && 'alpha' || 'beta' }}
      ref: ${{ github.event.workflow_run.head_sha }}
    secrets: inherit
